test_that("Removing all comments from knitr chunks works", {

  chunk <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```")
  exp <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```",
             "# BBBBBBBBBB",
             "",
             "BBBBBBBBBB",
             "")
  exp <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```",
           "# BBBBBBBBBB",
           "",
           "BBBBBBBBBB",
           "")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("# AAAAAAAAAA",
             "",
             "AAAAAAAAAA",
             "",
             "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```")
  exp <- c("# AAAAAAAAAA",
           "",
           "AAAAAAAAAA",
           "",
           "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("# AAAAAAAAAA",
             "",
             "AAAAAAAAAA",
             "",
             "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```",
             "# BBBBBBBBBB",
             "",
             "BBBBBBBBBB",
             "")
  exp <- c("# AAAAAAAAAA",
           "",
           "AAAAAAAAAA",
           "",
           "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```",
           "# BBBBBBBBBB",
           "",
           "BBBBBBBBBB",
           "")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```",
             "# BBBBBBBBBB",
             "",
             "BBBBBBBBBB",
             "",
             "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('More text!')",
             "",
             "# Test comment 3",
             "```")
  exp <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```",
           "# BBBBBBBBBB",
           "",
           "BBBBBBBBBB",
           "",
           "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
           "cat('More text!')",
           "",
           "```")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("# AAAAAAAAAA",
             "",
             "AAAAAAAAAA",
             "",
             "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```",
             "# BBBBBBBBBB",
             "",
             "BBBBBBBBBB",
             "",
             "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('More text!')",
             "",
             "# Test comment 3",
             "```")
  exp <- c("# AAAAAAAAAA",
           "",
           "AAAAAAAAAA",
           "",
           "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```",
           "# BBBBBBBBBB",
           "",
           "BBBBBBBBBB",
           "",
           "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
           "cat('More text!')",
           "",
           "```")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("# AAAAAAAAAA",
             "",
             "AAAAAAAAAA",
             "",
             "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```",
             "# BBBBBBBBBB",
             "",
             "BBBBBBBBBB",
             "",
             "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('More text!')",
             "",
             "# Test comment 3",
             "```",
             "# CCCCCCCCCC",
             "",
             "CCCCCCCCCC",
             "")
  exp <- c("# AAAAAAAAAA",
           "",
           "AAAAAAAAAA",
           "",
           "```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```",
           "# BBBBBBBBBB",
           "",
           "BBBBBBBBBB",
           "",
           "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
           "cat('More text!')",
           "",
           "```",
           "# CCCCCCCCCC",
           "",
           "CCCCCCCCCC",
           "")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```",
             "# AAAAAAAAAA",
             "",
             "AAAAAAAAAA",
             "",
             "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('More text!')",
             "",
             "# Test comment 3",
             "```")
  exp <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
           "cat('Be careful with your spacing in _Markdown_ documents.",
           "While whitespace largely is ignored, it does at",
           "times give _Markdown_ signals as to how to proceed.  ",
           "')",
           "",
           "```",
           "# AAAAAAAAAA",
           "",
           "AAAAAAAAAA",
           "",
           "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
           "cat('More text!')",
           "",
           "```")
  ret <- remove_comments_from_chunks(chunk)
  expect_identical(ret, exp)
  # ---------------------------------------------------------------------------
  chunk <- c("```{r chap01-para-6-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Be careful with your spacing in _Markdown_ documents.",
             "While whitespace largely is ignored, it does at",
             "times give _Markdown_ signals as to how to proceed.  ",
             "')",
             "",
             "# Test comment 3",
             "```",
             "```{r chap01-para-7-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('More text!')",
             "",
             "# Test comment 3",
             "```",
             "```{r chap01-para-8-en, eval = !fr(), results = 'asis'}",
             "# Test comment",
             "#Test Comment 2",
             "cat('Even more text!')",
             "",
             "# Test comment 3",
             "```")

})
